networks:
  mt-network:
    name: mt-network
    driver: bridge

services:

  mt-backend:
    image: hack-backend
    build:
      context: ./backend
      target: builder
    container_name: hack-backend
    networks:
      - mt-network
    env_file:
      - .env
    environment:
      PORT: 80
      MAX_WORKERS: 1
    ports:
      - '80:80'
      - '5678:5678'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

  mongo:
    image: mongo:latest
    container_name: hack-mongo
    networks:
      - mt-network
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data: